// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClCv4e_KGzzgIpqvwlV4h-1Q4JAuy4-qk',
    appId: '1:686367779623:web:051c0828e51205d0695702',
    messagingSenderId: '686367779623',
    projectId: 'trace-24c6f',
    authDomain: 'trace-24c6f.firebaseapp.com',
    storageBucket: 'trace-24c6f.appspot.com',
    measurementId: 'G-0QG65BYETS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDd7TeotzMM-kV-TaV95RUOBbMR9g3IfZo',
    appId: '1:686367779623:android:a416a671556f4e9c695702',
    messagingSenderId: '686367779623',
    projectId: 'trace-24c6f',
    storageBucket: 'trace-24c6f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlIU5f3EPSPfpteGyp0kbPTTa6Rvgrtyo',
    appId: '1:686367779623:ios:dcd55ea4a406c5ca695702',
    messagingSenderId: '686367779623',
    projectId: 'trace-24c6f',
    storageBucket: 'trace-24c6f.appspot.com',
    iosClientId: '686367779623-uoc1kpbksn3nsqp51rfr1651f8418a18.apps.googleusercontent.com',
    iosBundleId: 'com.example.fragileitemtrackingapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlIU5f3EPSPfpteGyp0kbPTTa6Rvgrtyo',
    appId: '1:686367779623:ios:dcd55ea4a406c5ca695702',
    messagingSenderId: '686367779623',
    projectId: 'trace-24c6f',
    storageBucket: 'trace-24c6f.appspot.com',
    iosClientId: '686367779623-uoc1kpbksn3nsqp51rfr1651f8418a18.apps.googleusercontent.com',
    iosBundleId: 'com.example.fragileitemtrackingapp',
  );
}
